from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

# Create your views here.

# # FUNCTION VIEW
# def function_view(request):
#     context = {
#         'page_title': 'Function-Based View',
#         'page_heading': 'Welcome to the Function-Based View',
#         'page_content': 'This is the content generated by the function-based view.',
#     }
#     return render(request, 'bootswatch.html', context)

# CLASS VIEW
class Home(View):
    def get(self, request):
        context = {
            'page_title': 'Class-Based View',
            'page_heading': 'Welcome to the Home page',
            'page_content': 'This is the content generated by the class-based view.',
            'image_url': '/static/images/django_logo.png',
            'alt_text': 'django logo',
        }
        return render(request, 'bootswatch.html', context)

# CLASS VIEW
class About(View):
    def get(self, request):
        context = {
            'page_title': 'Class-Based View',
            'page_heading': 'Welcome to the About page',
            'page_content': 'This is the content generated by the class-based view.',
            'image_url': '/static/images/person_pic.png',
            'alt_text': 'a computer generated photo of a person in a coffe shop working at a computer',
        }
        return render(request, 'bootswatch.html', context)

# CLASS VIEW
class Llamas(View):
    def get(self, request):
        context = {
            'page_title': 'Class-Based View',
            'page_heading': 'Welcome to the Llama page',
            'page_content': 'This is the content generated by the class-based view.',
            'image_url': '/static/images/llama_pic.png',
            'alt_text': 'a computer generated photo of a llama wearing glasses',
        }
        return render(request, 'bootswatch.html', context)

# CLASS VIEW
class Cats(View):
    def get(self, request):
        context = {
            'page_title': 'Class-Based View',
            'page_heading': 'Welcome to the Cats page',
            'page_content': 'This is the content generated by the class-based view.',
            'image_url': '/static/images/cat_pic.png',
            'alt_text': 'a computer generated photo of a cat in a library',
        }
        return render(request, 'bootswatch.html', context)